

export const dummy_table5 = [
  {
    "sl_number":"1",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "2",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "3",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "4",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "5",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "6",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",  },
  {
    "sl_number": "7",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "8",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "9",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "10",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "11",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "12",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "13",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "14",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "15",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "16",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "17",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "18",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "19",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "20",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
  {
    "sl_number": "21",
    "employee name":"Shreeram",
    "role":"Physiotherapist",
    "time line":"22 Feb 22-24 Feb 22",
    "type":"leave",
    "reason":"Ament minim mont non desurant",
    "action":"Tick",
  },
];

export const dummy_table_mapping5 = [
  [
    "Sl. No.",
    "Employee Name",
    "Role",
    "Time Line",
    "Type",
    "Reason",
    
    "Action",
  ],
  [
    "sl_number",
    "employee name",
    "role",
    "time line",
    "type",
    "reason",
    "action",
  ],
];
