import Switch from "../pages/UserManagment/toggel";

export const dummy_table1 = [
  {
    sl_number: "1",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "2",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "3",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "4",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "5",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "6",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "7",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "8",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "9",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "10",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "11",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "12",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "13",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "14",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "15",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "16",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "17",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "18",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "19",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "20",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
  {
    sl_number: "21",
    user_ID: "VSN50652",
    "Full Name": "Jacob Jones",
    Mobile_No: "+60 564531",
    Role: "Driver",
    "Last Active": "22 Feb 22 - 4:20 pm",
    activate: <Switch />,
    Action: "Edit",
  },
];

export const dummy_table_mapping1 = [
  [
    "Sl. No.",
    "user ID",
    "Full Name",
    "Mobile No",
    "Role",
    "Last Active",
    "Activate",
    "Action",
  ],
  [
    "sl_number",
    "user_ID",
    "Full Name",
    "Mobile_No",
    "Role",
    "Last Active",
    "activate",
    "Action",
  ],
];
